configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/nerft.yaml # network model configuration
    - configs/specs/plain.yaml # network model configuration
    - configs/datasets/NHR/sport1.yaml # dataset usage configuration
    - configs/specs/static.yaml # specific usage configuration

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
