configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/enerfi.yaml # network model configuration
    - configs/datasets/enerf_outdoor/actor2_3.yaml # dataset usage configuration
    - configs/specs/optimized.yaml

dataloader_cfg:
    dataset_cfg: &dataset_cfg # ratio: 0.5
        frame_sample: [0, 300, 1] # use the first 300 frames for training

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
        frame_sample: [0, 1200, 100]
    sampler_cfg:
        view_sample: [0, 18, 17] # 0 and 17

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
