configs: configs/datasets/mipnerf360/mipnerf360.yaml

dataloader_cfg:
    dataset_cfg: &dataset_cfg
        data_root: data/mipnerf360/kitchen

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg

viewer_cfg:
    camera_cfg:
        K: [[2466.0, 0.0, 683.0], [0.0, 2466.0, 384.0], [0.0, 0.0, 1.0]]
        # prettier-ignore
        R: [[0.9999675750732422,0.008049854077398777,-0.0],[-0.00804910622537136,0.9998746514320374,-0.01356500107795],[-0.00010919627675320953,0.013564561493694782,0.9999070763587952]]
        T: [[0.40995997190475464], [-1.5854984521865845], [5.6753435134887695]]
        n: 3.5799999237060547
        f: 100.0
        world_up: [0.00804910622537136, -0.9998746514320374, 0.01356500107795]
# {"H":768,"W":1366,"K":[[2466.0,0.0,683.0],[0.0,2466.0,384.0],[0.0,0.0,1.0]],"R":[[0.9999675750732422,0.008049854077398777,-0.0],[-0.00804910622537136,0.9998746514320374,-0.01356500107795],[-0.00010919627675320953,0.013564561493694782,0.9999070763587952]],"T":[[0.40995997190475464],[-1.5854984521865845],[5.6753435134887695]],"n":3.5799999237060547,"f":100.0,"t":0.0,"v":0.0,"bounds":[[-10.0,-10.0,-10.0],[10.0,10.0,10.0]],"mass":0.10000000149011612,"moment_of_inertia":0.10000000149011612,"movement_force":1.0,"movement_torque":1.0,"movement_speed":1.0,"origin":[0.0,0.0,0.0],"world_up":[0.0,0.0,1.0]}
