# Supercharged model only
configs: configs/specs/vis.yaml
model_cfg:
    sampler_cfg:
        skip_loading_points: True
        points_expanded: True
        points_aligned: True

val_dataloader_cfg:
    dataset_cfg:
        barebone: True
        use_vhulls: False
        skip_loading_images: True
