# Configuration for ENeRF on enerf_outdoor actor 1
# This is literally an empty file
configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/enerf.yaml # network model configuration
    - configs/datasets/genebody/mahaoran.yaml # dataset usage configuration
    - configs/specs/mask.yaml # dataset usage configuration

val_dataloader_cfg:
    dataset_cfg: &dataset_cfg
        n_srcs_list: [2, 3]
        n_srcs_prob: [0.5, 0.5]
        n_render_views: 1000
        view_sample: [0, null, 1] # will get overwritten by orbit.yaml, need to specify in commandline
        ratio: 0.5 # use 0.5 for this
        bounds: [[-5.0, -5.0, -5.0], [5.0, 5.0, 5.0]] # thinner?
        near: 0.002 # no need for this if using vhull
        far: 10.0 # a large value

dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
    batch_sampler_cfg:
        batch_size: 1

# model_cfg:
#     sampler_cfg:
#         n_samples: [8, 2]
#         n_planes: [32, 8]

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
# NOTE: only define something in one place
