configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/r4dv.yaml # network model configuration
    - configs/datasets/my_zjumocap/my_377_obj.yaml # dataset usage configuration
    - configs/specs/mask.yaml # specific usage configuration
    - configs/specs/optimized.yaml # specific usage configuration
    - configs/specs/legacy.yaml # MARK: this is an old model
    - configs/specs/superf.yaml # NOTE: real-time rendering

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
