configs: configs/datasets/genebody/genebody.yaml
dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        data_root: data/genebody/genebody_test10/barry

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
