configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/l3mhet.yaml # network model configuration
    - configs/datasets/st_nerf/taekwondo.yaml # dataset usage configuration
    - configs/specs/static.yaml
    - configs/specs/optcam.yaml
    - configs/specs/transient.yaml

dataloader_cfg: # we see the term "dataloader" as one word?
    dataset_cfg: &dataset_cfg
        near: 2.5
        far: 10.0
        bounds: [[-4.0, -3.0, -2.0], [4.0, 3.0, 4.0]]

val_dataloader_cfg:
    dataset_cfg:
        <<: *dataset_cfg
    sampler_cfg:
        view_sample: [0, null, 5]

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
