configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/l3mhet.yaml # network model configuration
    - configs/datasets/renbody/0021_01.yaml # dataset usage configuration
    - configs/specs/mask.yaml
    - configs/specs/static.yaml
    - configs/specs/optcam.yaml
    - configs/specs/transient.yaml

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
