configs:
    - configs/base.yaml # default arguments for the whole codebase
    - configs/models/l3mhet.yaml # network model configuration
    - configs/datasets/enerf_outdoor/actor2_3.yaml # dataset usage configuration
    - configs/specs/static.yaml
    - configs/specs/optcam.yaml
    - configs/specs/transient.yaml
    - configs/specs/optimized.yaml

dataloader_cfg: &dataloader_cfg
    dataset_cfg:
        images_dir: bkgd/images

val_dataloader_cfg: *dataloader_cfg

# prettier-ignore
exp_name: {{fileBasenameNoExtension}}
